### ISSUE TITLE
Try and stick to CRUD 

### ISSUE THREAD

**Issue by njoguamos** [ivikee7/SchoolERP#12]
When you find yourself creating primary actions that are not `index`, `create`, `store`, `show`, `edit`, `update` or `destroy` then it is time to refactor into a new controller.

For example, this code

https://github.com/ivikee7/SchoolERP/blob/7f2590285b907cf185ec19d79e6ec0a5fa6670ee/app/Http/Controllers/UserController.php#L344-L347

Can be extracted in a `UserProfileController`

```php
class UserProfileController extends Controller
{
    public function index() 
    { 
         return view('profile')->with(['user' => Auth()->user()]); 
    } 
}
```

**Comment by ivikee7** [comment]
done
